# 예외처리

## error와 exception

* error: 하드웨어 고장등으로 인해 응용프로그램 실행 오류가 발생. JVM실행에 문제가 생긴것이므로 코드랑 무관하게 실행불능.
* exception: 잘못된 코드나 사용자의 잘못된 조작으로 인해 발생하는 프로그램 오류. 에러와 차이점은 에러가 발생되면 프로그램이 종료된다는 것이지만 예외는 예외 처리를 통해 프로그램을 종료하지 않고 정상 실행 상태가 유지되도록 할 수 있음.

## exception은 2가지로 나뉜다

* 일반 예외(Exception): 컴파일 하는 과정에서 예최처리코드가 필요한지 검사, 예외처리 코드가 없다면 컴파일 오류가 발생.
* 실행 예외(Runtime Exception): 컴파일하는 과정에서 예외 처리 코드를 검사하지 않는 예외, 자바 컴파일러가 체크를 하지 않기 때문에 오로지 개발자의 경험에 의해서 예외 처리 코드를 삽입해야하며, 만약 실행 예외에 대한 예외 처리 코드를 넣지 않았을 경우, 해당 예외가 발생하면 프로그램은 바로 종료.

## 여러 가지 exception

### NullPointerException

null값을 갖는 참조 변수로 객체 접근 연산자인 도트(.)를 사용했을 때 발생한다. 객체가 없는 상태에서 객체를 사용하려 한것이므로 예외가 발생한 것이다.

```java

public class JavaStudy
{
  public static void main(String[] args){
    String data = null;
    System.out.println(data.toString());  //예외 발생
  }
}

```

### ArrayIndexOutOfBoundsException

배열에서 인덱스 범위를 초과하여 사용할 경우.

```java

public class JavaStudy
{
  public static void main(String[] args){
    int[] text = {1, 2, 3};
    System.out.println(test[3]);  //예외 발생
  }
}

```

### NumberFormatException

문자열 데이터를 숫자로 변경할 때 숫자로 변환될 수 없는 문자가 포함되어 있을 때 발생

```java

public class JavaStudy
{
  public static void main(String[] args){
    String data = 'a100;
    int value = Integer.parseInt(data);  //예외 발생
  }
}

```

### ClassCastException

클래스 간 잘못된 타입 변환을 했을 때 발생.

```java

public class JavaStudy
{
  public static void main(String[] args){
    Animal animal = new Dog();
    Cat cat = (Cat) animal;  //예외 발생
  }
}

class Animal {
  ...
}

class Dog extends Animal {
  ...
}

class Cat extends Animal {
  ...
}

```

## catch 순서

다중 catch블록을 작성할 때 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다.
try블록에서 예외가 발생했을 때, 예외를 처리해 줄 catch 블록은 위엥서부터 차례돼로 검색되기 때문이다.
예를 들어 아래와 같이 코딩했을 때 try문의 어떤 예외가 발새하든 모든 예외는 Exception을 상속받기 때문에 그 아래 catch 문은 실행되지 못하고 첫번째 catch만 실행되게 된다.

```java

public class JavaStudy
{
  public static void(String[] args){
    try {
      //ArrayIndexOutOfBoundsException 발생
      
      //NumberFormatException 발생
    } catch (Exception e) {
      ...
    } catch (ArrayIndexOutOfBoundsException e) {
      ...
    } catch (NumberFormatException e) {
      ...
    }
  }
}

```

## 자동 리소스 닫기

자동 리소스 닫기 기능이 있기 전까지 리소스 객체를 안전하게 닫기 위해서는 다음과 같이 사용했다.

```java

public class JavaStudy
{
  public static void main(String[] args){
    FileInputStream fis = null;
    try {
      fis = new FileInputStream("file.txt");
    } catch (IOException e) {
      ...
    } finally {
      if (fis != null) {
        try {
          fis.close();  //이런 식으로 안전하게 닫아주었다.
        } catch (IOException e) {
          ...
        }
      }
    }
  }
}

```

이걸 try-with-resources를 사용하면

```java

public class JavaStudy
{
  public static void main(String[] args){
    try (FileInputStream fis = new FileInputStream("file.txt")) {  //이런식으로 간단히 한줄로 줄일 수 있다.
      ...
    } catch (IOException e) {
      ...
    }
  }
}

```

## 예외 떠넘기기 throws

throws는 메소드 선언부 끝에 작성되어 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역할을 한다.
thorws 키워드 뒤에는 떠넘길 예외 클래스를 쉼표로 구분해서 나열해주면 된다.

```java
리턴타입 메소드명(매개변수...) throws 예외클래스1, 예외클래스2 {}
```

발생할 수 있는 예외의 종류별로 throws 뒤에 나열하는 것이 일반적이지만, 다음과 같이 throws Exception만으로 모든 예외를 간단히 떠넘길 수도 있다.

```java
리턴타입 메소드명(매개변수...) throws Exception {}
```

> throws 키워드가 붙어있는 메소드는 반드시 try 블록 내에서 호출되어야 한다.
그리고 catch 블록에서 떠넘겨 받은 예외를 처리해야 한다. 아니면 throws를 다시 사용해서 예외를 호출한 곳으로 또 떠넘겨줘야한다.
결국 언젠가는 try-catch문에서 다뤄줘야한다.
